name: whatsapp_stickers
description: WhatsApp Stickers plugin for Flutter.
version: 0.1.0-nullsafety.0
homepage: https://github.com/applicazza/whatsapp_stickers

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.3.0'


dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.applicazza.flutter.plugins.whatsapp_stickers
        pluginClass: WhatsappStickersPlugin
      ios:
        pluginClass: WhatsappStickersPlugin
